---
- name: Write the custom sysctl settings
  ansible.builtin.template:
    src: 99-custom.conf.j2
    dest: /etc/sysctl.d/99-custom.conf
    owner: root
    group: root
    mode: "0644"
  notify: Reload sysctl
