#!/usr/bin/env bash
# Set (or rotate) user's EMERGENCY console password.
#
# Run this ONCE — re-run only to change the password. It hashes the password you
# type and stores the hash in ansible/secrets.local.yml (gitignored, mode 600),
# which apply.sh auto-loads. You do NOT enter the password on every apply: each
# apply just re-asserts the stored hash idempotently.
#
# The plaintext you type is what you log in with at the Vultr web console /
# serial (SSH password auth is off, so it's console-only). SAVE IT in your
# password manager now — only its one-way hash is stored and it can't be
# reversed. Lose it and you must run this again to set a new one.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SECRETS="$ROOT/ansible/secrets.local.yml"

command -v openssl >/dev/null 2>&1 || { echo "openssl is required." >&2; exit 1; }

read -rsp "New emergency password for user: " PW; echo
read -rsp "Confirm password: " PW2; echo
[ -n "$PW" ]        || { echo "Empty password — aborting." >&2; exit 1; }
[ "$PW" = "$PW2" ]  || { echo "Passwords did not match — aborting." >&2; exit 1; }

# sha512crypt ($6$) hash. -stdin keeps the plaintext off the process list.
HASH="$(printf '%s' "$PW" | openssl passwd -6 -stdin)"
unset PW PW2

umask 077
cat > "$SECRETS" <<EOF
---
# AUTO-GENERATED by set-emergency-password.sh — gitignored, DO NOT commit.
# sha512crypt hash of user's emergency console password.
user_password_hash: '$HASH'
EOF

echo
echo "Wrote $SECRETS"
echo "Apply it now with:   sudo bash apply.sh"
echo "  (or just the accounts role:  cd ansible && ansible-playbook -i 'localhost,' -c local site.yml --tags accounts)"
