---
galaxy_info:
  role_name: accounts
  author: cschlick
  description: Ensure required user accounts exist and fully purge unwanted ones
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Debian
      versions:
        - trixie
dependencies: []
