---
galaxy_info:
  role_name: ghostty_terminfo
  author: cschlick
  description: Make Debian's Ghostty terminfo available as xterm-ghostty
  license: MIT
  min_ansible_version: "2.14"
dependencies: []
