---
- name: Install Greasewood globally
  ansible.builtin.command:
    argv:
      - pipx
      - install
      - --global
      - --force
      - git+https://github.com/cschlick/greasewood.git@main
  changed_when: true
